### ISSUE TITLE
This isn't original

### ISSUE THREAD

**Issue by mapleint** [rezadfx/HWID-shifter#3]
The spoofer part is part of namazso's 3 year old hdd serial spoofer, applying the exact same technique
Maybe I am stupid, but when I read clear traces I usually think of MmUnloadedDrivers and PiDDBtable
It's dishonest to remove namaszo's name from the spoofer, toss your discord in there too.

**Comment by Xenia0** [comment]
Infact mapleint is correct, this looks like a paste from namazso's hdd serial spoofer with some minor modification.
